openapi: 3.0.0

info:
  title: Novaxcape Tourist API
  version: 1.0.0
  description: Documentation for tourist endpoints

paths:

  /api/v1/tourist/register:
    post:
      summary: Register tourist center
      tags:
        - Tourist

      security:
        - bearerAuth: []

      requestBody:
        required: true
        context:
          multipart/form-data:
            schema:
              type: object
              required:
                - centreName
                - description
                - location
                - state
                - openingHours
                - images
                - city
                - installmentPayment
                - streetAddress
                - facilitiesAndAmenities
                - dailySlotCapacity
                - privacyPolicy
              properties:
                centreName:
                  type: string
                  example: Lekki Conservation Center

                description:
                  type: string
                  example: A nature reserve located in Lagos, Nigeria, known for its rich biodiversity and conservation efforts.

                location:
                  type: string
                  example: Lekki, Lagos
                
                state:
                  type: string
                  example: Lagos

                openingHours:
                  type: string
                  example: 9:00 AM - 6:00 PM

                images:
                  type: string

                city:
                  type: string
                  example: Lagos

                installmentPayment:
                  type: boolean
                  example: true

                streetAddress:
                  type: string
                  example: 123 Lekki Road, Lagos

                facilitiesAndAmenities:
                  type: string
                  example: Picnic areas, boardwalks, birdwatching towers, and a canopy walkway

                dailySlotCapacity:
                  type: integer
                  example: 100

                privacyPolicy:
                  type: string
                  

      responses:
        "201":
          description: Tourist center registered successfully

  /api/v1/tourist/get-all-state/{state}:
    get:
      summary: Get tourist centers by state
      description: Returns all tourist centers registered in the requested state.
      operationId: getAllTouristsByState
      tags:
        - Tourist
      parameters:
        - in: path
          name: state
          required: true
          description: State to filter tourist centers by.
          schema:
            type: string
          example: Lagos
      responses:
        "200":
          description: Centers found
        "404":
          description: No centers found in the requested state
        "500":
          description: Something went wrong
